// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function GetChildren(arg1) {
  return window['go']['main']['App']['GetChildren'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConnectionTypes() {
  return window['go']['main']['App']['ListConnectionTypes']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
