// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CreateConnection(arg1:core.ConnectionConfig):Promise<core.ConnectionConfig>;

export function GetChildren(arg1:string):Promise<Array<core.TreeNode>>;

export function Greet(arg1:string):Promise<string>;

export function ListConnectionTypes():Promise<Array<core.ConnectionType>>;

export function ListConnections():Promise<Array<core.ConnectionConfig>>;

export function TestConnection(arg1:core.ConnectionConfig):Promise<void>;
